#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace org.kharynic
{
    // replaced during build by code generated by org.kharynic.Editor.BuildInfo.Generator
    // used only for in-editor preview which doesn't run generators
    public partial class BuildInfo
    {
        private static string GetEditorPreviewBuildVersion()
        {
            var filePath = Application.dataPath + "/Editor/BuildInfo.Version.txt";
            // major.minor.build+hash
            var version = File.ReadAllText(filePath).Split('.', '+').ToArray();
            version[2] = (int.Parse(version[2]) + 1).ToString();
            version[3] = Guid.NewGuid().GetHashCode().ToString("x8").Substring(0, 3);
            var versionString = $"{version[0]}.{version[1]}.{version[2]}+{version[3]}_preview";
            return versionString;
        }
        
        public static readonly IEnumerable<string> DefinedSymbols = new[]{"UNITY_EDITOR"};
        public static readonly string Platform = "UnityEditor/" + EditorUserBuildSettings.activeBuildTarget;
        public static readonly string Runtime = ScriptingImplementation.Mono2x.ToString();
        public static readonly string TranspilationTarget = "CIL";
        public static readonly string BuildDate = DateTime.Now.ToString("MMM dd yyyy", CultureInfo.InvariantCulture);
        public static readonly string User = (Environment.UserName + "@" + Environment.UserDomainName).ToLowerInvariant();
        public static readonly string LocalAssetsPath = Application.dataPath;
        public static string Version = GetEditorPreviewBuildVersion();
    }
}
#endif
