#if UNITY_EDITOR
namespace org.kharynic
{
    // Replaced during build by code generated by org.kharynic.Editor.EngineExternals.Generator.
    // Used only for in-editor preview which doesn't run generators.
    public static partial class EngineExternals
    {
        public class Wrappers
        {
            
        }
    }
}
#endif
